// // console.log("Hi");
// // console.log("Codding  is " + "Fun for people ");
// var found = true;
// var grader = 88.6;
// var firstname = 'David';
// var lastname = 'Fashola';
// console.log(found);
// console.log("The grade is " + grader);
// console.log("My name is " + firstname + " " + lastname);
// // let myData: any 50.0;
// // myData = false;
// // myData = 'Eric';
// // myData = '19';
