// // console.log("Hi");
// // console.log("Codding  is " + "Fun for people ");
// let found: boolean = true;
// let grader: number = 88.6;
// let firstname: String = 'David';
// let lastname:String = 'Fashola';
// console.log(found);
// console.log("The grade is " + grader);
// // console.log("My name is " + firstname + " " + lastname);
// console.log(`My name is ${firstname} ${lastname}`);
// // let myData: any 50.0;
// // myData = false;
// // myData = 'Eric';
// // myData = '19';